export const GET_ORDERS_USER = 'Orders/GET_ORDERS_USER';
export const GET_ORDER_SUCCESS = 'Orders/GET_ORDER_SUCCESS';
export const SET_ORDER_SUCCESS = 'Orders/SET_ORDER_SUCCESS';
export const SET_ORDERS_USER = 'Orders/SET_ORDERS_USER';
export const CANCEL_TRANSCACTION = 'Orders/CANCEL_TRANSCACTION';
